### ISSUE TITLE
antd5.x.0及以上的版本无法通过@ant-design/cssinjs在低版本浏览器上实现Message组件和Notification组件样式降级

### ISSUE THREAD

**Issue by xuehaiouyang** [ant-design/cssinjs#113]
`return React.createElement(
    StyleProvider,
    {
      hashPriority: 'high',
      transformers: [legacyLogicalPropertiesTransformer],
    },
    container,
  );`
目前发现就这两个组件，没有降级，还是用:where()包裹

**Comment by xuehaiouyang** [comment]
ant-design/cssinjs 版本为1.9.1

**Comment by ifreeWorld** [comment]
> ant-design/cssinjs 版本为1.9.1

我也发现一样的问题，请问现在是否已经解决了，如果已经解决了，可否分享一下解决方案，谢谢

**Comment by jiajiaxing1** [comment]
+1  后续怎么解决的呐

**Comment by nirvana-for-ever** [comment]
npm ls @ant-design/cssinjs
检查一下是不是装了多个版本

**Comment by iterminatorheart** [comment]
这个原因是message组件默认不消费context导致的，官方解释在这里：https://ant-design.antgroup.com/components/message-cn#faq

所以要使得Message组件降级生效需要这样写代码：

```
const App = () => {
   const [api, contextHolder] = message.useMessage();

    useEffect(() => {
        api.info('some test info');
    }, []);

   return (
       <StyleProvider transformers={[legacyLogicalPropertiesTransformer]} hashPriority="high">
         {contextHolder}
      </StyleProvider>
   )
}
```
关键点就是通过调用useMessage获得message的占位节点，将占位节点放在StyleProvider组件之内，让其能正确的消费到context信息
