### ISSUE TITLE
useGlobalCache TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by idaaaaaaa** [ant-design/cssinjs#127]
It happens when the route change, not 100% but it's easy to reproduce
![image](https://github.com/ant-design/cssinjs/assets/132628076/06f1b91a-e869-4393-9f0f-e9cef9d030de)

**Comment by rafaewaqarqazi** [comment]
I am also getting this error
![image](https://github.com/ant-design/cssinjs/assets/28054812/2d739a24-ea78-4bfb-8794-c761a34851e8)

**Comment by idaaaaaaa** [comment]
![image](https://github.com/ant-design/cssinjs/assets/132628076/9bb871fd-d303-49be-893e-c27f1c162a7b)
I moved `const cache = createCache();` outside the StyledComponentsRegistry and it works fine now

**Comment by RoudyTarabay** [comment]
> ![image](https://user-images.githubusercontent.com/132628076/255045129-9bb871fd-d303-49be-893e-c27f1c162a7b.png) I moved `const cache = createCache();` outside the StyledComponentsRegistry and it works fine now

Thank you. Fixed it for me. The docs should be updated

**Comment by afc163** [comment]
@zombieJ
