### ISSUE TITLE
linters should be removed in production

### ISSUE THREAD

**Issue by afc163** [ant-design/cssinjs#163]
![图片](https://github.com/ant-design/cssinjs/assets/507615/9725784a-d142-43b5-839c-ff5223572c76)

**Comment by MadCcc** [comment]
antd 打包 antd.js 时 mode 时 `development`, antd.min.js 里就没有 linters 了

**Comment by afc163** [comment]
<img width="1406" alt="图片" src="https://github.com/ant-design/cssinjs/assets/507615/1854ae9e-c694-42c2-9feb-d87f28f93296">
这是还有么？
