### ISSUE TITLE
useGlobalCache 会产生内存泄漏

### ISSUE THREAD

**Issue by blackie4** [ant-design/cssinjs#188]
[useGlobalCache](https://github.com/ant-design/cssinjs/blob/master/src/hooks/useGlobalCache.tsx#L26) 会产生内存泄漏，可以看官网Demo https://ant-design.antgroup.com/components/button-cn，然后查看Memory堆栈信息
![token-cache](https://github.com/user-attachments/assets/d0c1556a-27fb-425b-ae24-682fbc1ee28e)

**Comment by Junlin-Zhu** [comment]
我在生产上也遇到了类似的问题，有官方的解法么？

**Comment by zjfjiayou** [comment]
同样的问题，求修复
