### ISSUE TITLE
useStyles产生的内存泄漏问题

### ISSUE THREAD

**Issue by langzhi827** [ant-design/cssinjs#197]
在使用antd组件以及自己组件内使用useStyles API的时候，每次组件render都会导致内存飙升，页面足够复杂的时候很容易导致内存泄露问题。
发现可能是由于`src/hooks/useEffectCleanupRegister.ts`文件中通过的useEffect监听对cache清理的逻辑频繁触发导致，希望尽快处理，不胜感激！
![WX20240925-165703](https://github.com/user-attachments/assets/ff770cf5-0faa-4330-a983-1fdeb5bfa8a1)
![WX20240925-165726](https://github.com/user-attachments/assets/268ba9fb-4f24-4803-baca-4850e3e3ded4)

**Comment by afc163** [comment]
来个 PR？

**Comment by langzhi827** [comment]
> 来个 PR？

Fix: https://github.com/ant-design/cssinjs/pull/198

**Comment by zjfjiayou** [comment]
![image](https://github.com/user-attachments/assets/83850ff9-8ef0-4739-ad12-6178baa77a50)
遇到同样的问题
