### ISSUE TITLE
extraStyle with layer result in duplicated "@layer antd" for table style

### ISSUE THREAD

**Issue by kennedy0527** [ant-design/cssinjs#206]
先附上 [codesandbox](https://codesandbox.io/p/devbox/6522p7)

在nextjs 專案內 使用@ant-design/nextjs-registry
sample code如下
```jsx
<AntdRegistry layer>
    <Provider>{children}</Provider>
</AntdRegistry>
```
Provider 是另外封裝的 Antd ConfigProvider

瀏覽頁面 AntdRegistry 成功建立了一個Style tag with id `antd-cssinjs` 
但將其內容 複製出來 format後 檢查 發現table 的樣式 會多一個 `@layer antd `
這導致Table 沒辦法吃到 custom theme

刪除其中一個 `@layer antd` 就正常了
<img width="853" alt="Screenshot 2024-12-02 at 7 23 57 PM" src="https://github.com/user-attachments/assets/38f438e3-7468-47a1-be58-66e8a1dfdceb">

不確定是否是cssinjs 的問題，暫時先發在這裡

**Comment by Wxh16144** [comment]
fixed  by #207

**Comment by kennedy0527** [comment]
confirmed
thank you very much @Wxh16144
