### ISSUE TITLE
useHMR 的 hack 用法导致在 vite 上无法运行，间接导致 pro-components v2 无法在 vite 上运行

### ISSUE THREAD

**Issue by sushi-su** [ant-design/cssinjs#46]
commit #43

**Comment by sushi-su** [comment]
代码示例：https://stackblitz.com/edit/vitejs-vite-xwk7be?file=package.json

**Comment by sushi-su** [comment]
![image](https://user-images.githubusercontent.com/50985188/190885431-9b11a03b-91aa-461d-a885-9b13ecb080b9.png)
![image](https://user-images.githubusercontent.com/50985188/190885440-849758cd-fd7e-4d4e-bc42-d2c753171eea.png)

**Comment by 1589625130** [comment]
你好，你得解决了吗

**Comment by sushi-su** [comment]
@1589625130  pnpm i @ant-design/cssinjs@0.0.0-alpha.45

**Comment by 1589625130** [comment]
谢谢
