### ISSUE TITLE
Demo Website isn't working

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [ant-design/cssinjs#54]
![image](https://user-images.githubusercontent.com/27003616/202838621-35cd5af4-c165-4415-8989-7bcdc56071a0.png)

**Comment by scharf** [comment]
Seeing the same error

**Comment by adamistheanswer** [comment]
Still not working

**Comment by viranmalaka** [comment]
still the same error!

**Comment by afc163** [comment]
See https://ant-design.github.io/cssinjs/
