### ISSUE TITLE
Missing condition to check if body is loaded at `StyleContext.tsx`

### ISSUE THREAD

**Issue by bougassaa** [ant-design/cssinjs#57]
Hello,
We are converting our React components to WebComponents (with AntDesign 4 everything worked fine). We've upgraded to V5, and when we build the React components then we include the built file in our sites written in pure HTML (included in the `<head>`).
But as in the screenshot below, an error is detected. I think the condition in file `src/StyleContext.tsx:13` is missing the `document.body` check, this will avoid some issues in the future, as V5 of antd has just been released.
I thank you for your work, and for the correction that you could bring 🙏.

<img width="797" alt="Capture d’écran 2022-11-16 à 16 00 01" src="https://user-images.githubusercontent.com/66357198/203074439-c5098a15-fcdd-42cd-99f0-031a6c6f9c73.png">

<img width="797" alt="Capture d’écran 2022-11-16 à 16 00 20" src="https://user-images.githubusercontent.com/66357198/203074477-c3f0e5b2-bb5c-4f7b-b2a2-3f135d51d5c4.png">

**Comment by daniele-serfilippi** [comment]
Having the same problem

**Comment by siamakmontazer** [comment]
I have exactly the same problem
