### ISSUE TITLE
cssinjs 出现 Warning: [Ant Design CSS-in-JS]

### ISSUE THREAD

**Issue by guopingxiao** [ant-design/cssinjs#71]
复现demo见： https://github.com/guopingxiao/cssinjs-demo

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/11886494/210380557-c338a53b-b974-4d47-81f6-369a42f3fd92.png">

**Comment by guopingxiao** [comment]
- 1. 启动 yarn && yarn start

- 2. 查看cssinjs版本为1.3.2
```
npm list @ant-design/cssinjs
rc-footer@0.6.6 /Users/xiaopingguo/Desktop/cssinjs-demo
├── @ant-design/cssinjs@1.3.2
├─┬ antd@5.1.2
│ └── @ant-design/cssinjs@1.3.2 deduped
└─┬ rc-footer@0.6.6 extraneous -> ./
  └── @ant-design/cssinjs@1.3.2 deduped
```

- 3. 使用方式为useStyleHooks

- 4. 启动后，查看simple, footer组件里使用的paddingLeft在控制台warning了

**Comment by zombieJ** [comment]
@MadCcc lint false ref 到这里
