### ISSUE TITLE
在umi4的项目上向后兼容样式出现了报错（360上用antd5样式错乱）

### ISSUE THREAD

**Issue by Atw-Lee** [ant-design/cssinjs#77]
packages:
"@ant-design/cssinjs": "^1.5.0",
"antd": "^5.1.1",
"umi": "^4.0.41"

参考：https://ant-design.antgroup.com/docs/react/compatible-style-cn#css-%E9%80%BB%E8%BE%91%E5%B1%9E%E6%80%A7

use：
// src/layouts/index.tsx
  return (
    <StyleProvider transformers={[legacyLogicalPropertiesTransformer]}>
      <div className={styles.container}>
        <Context.Provider value={contextValue}>
          <Outlet />
        </Context.Provider>
      </div>
    </StyleProvider>
  );

err:
- The above error occurred in the <StyleProvider> component:
- Uncaught TypeError: Cannot read properties of null (reading 'useContext')
- Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons

**Comment by Atw-Lee** [comment]
use：
<StyleProvider transformers={[legacyLogicalPropertiesTransformer]}>
      <div className={styles.container}>
        <Context.Provider value={contextValue}>
          <Outlet />
        </Context.Provider>
      </div>
    </StyleProvider>

**Comment by Atw-Lee** [comment]
use：
return (
    <StyleProvider transformers={[legacyLogicalPropertiesTransformer]}>
      <div className={styles.cscecTreasurerContainer}>
        <Context.Provider value={contextValue}>
          {!urlParams.hideHeader && (
            <Header
              setUnit={setUnit}
              unit={unit}
              setDate={setDate}
              date={date}
              setPeriodType={setPeriodType}
              periodType={periodType}
            />
          )}
          <Outlet />
        </Context.Provider>
      </div>
    </StyleProvider>
  );

**Comment by Atw-Lee** [comment]
<StyleProvider transformers={[legacyLogicalPropertiesTransformer]}>
      <div className={styles.cscecTreasurerContainer}>
        <Context.Provider value={contextValue}>
          {!urlParams.hideHeader && (
            <Header
              setUnit={setUnit}
              unit={unit}
              setDate={setDate}
              date={date}
              setPeriodType={setPeriodType}
              periodType={periodType}
            />
          )}
          <Outlet />
        </Context.Provider>
      </div>
    </StyleProvider>

**Comment by Atw-Lee** [comment]
报错问题解决了，将cssinjs的版本和antd的版本保持一致。
但360上的样式兼容还是不行

**Comment by Atw-Lee** [comment]
我引入了antd4的css文件

**Comment by UmbraCi** [comment]
> 报错问题解决了，将cssinjs的版本和antd的版本保持一致。 但360上的样式兼容还是不行
@ant-design/cssinjs这个包需要独立安装吗，我看到是antd的子依赖，但是我引用的时候报错找不到这个模块：pnpm的安装方式

**Comment by jiajiaxing1** [comment]
> 错问题解决了，将cssinjs的版本和antd的版本保持一致。

你好 怎么确定cssinjs和antd版本保持一致了？在哪里可以看到吗 
比如antd@5.8.x的版本 需要匹配什么版本的cssinjs?

**Comment by Atw-Lee** [comment]
很抱歉我忘记这是个啥bug了，从描述来看，我想表达的可能在项目中安装一下@ant-design/cssinjs这个包，版本和node_modules里antd里的@ant-design/cssinjs版本保存一致。

> > 错问题解决了，将cssinjs的版本和antd的版本保持一致。
> 
> 你好 怎么确定cssinjs和antd版本保持一致了？在哪里可以看到吗 比如[antd@5.8.x](mailto:antd@5.8.x)的版本 需要匹配什么版本的cssinjs?

**Comment by Atw-Lee** [comment]
> > 报错问题解决了，将cssinjs的版本和antd的版本保持一致。 但360上的样式兼容还是不行
> > @ant-design/cssinjs这个包需要独立安装吗，我看到是antd的子依赖，但是我引用的时候报错找不到这个模块：pnpm的安装方式

很抱歉现在才看到这个问题，无法引用是因为pnpm的问题，它无法引用项目中的非直接依赖。

**Comment by jiajiaxing1** [comment]
> 很抱歉我忘记这是个啥bug了，从描述来看，我想表达的可能在项目中安装一下@ant-design/cssinjs这个包，版本和node_modules里antd里的@ant-design/cssinjs版本保存一致。
> 
> > > 错问题解决了，将cssinjs的版本和antd的版本保持一致。
> > 
> > 
> > 你好 怎么确定cssinjs和antd版本保持一致了？在哪里可以看到吗 比如[antd@5.8.x](mailto:antd@5.8.x)的版本 需要匹配什么版本的cssinjs?

感谢
