### ISSUE TITLE
建议 readme 中的 install 改为文字，图片无法直接复制需要手打 

### ISSUE THREAD

**Issue by CrazyDiablo** [ant-design/cssinjs#97]
![WeChatbca045a2e449b7fe42a11b5bc457631a](https://user-images.githubusercontent.com/32573416/223327035-0bb76182-7b71-4f2e-b5a6-5f4ed2ce8bbd.png)

**Comment by Wxh16144** [comment]
2333, 好多 rc-xxx 都是这个模版.

**Comment by afc163** [comment]
https://github.com/ant-design/cssinjs/commit/5476be41bac0ccd7eb4d29a21d882c77bda8fc77

好了
